name: Recreate E2E Testing Branch

on:
  workflow_dispatch:

permissions:
  actions: write
  checks: write
  contents: write
  deployments: read
  id-token: write
  issues: read
  pull-requests: write
  statuses: read

jobs:
  recreate-e2e-testing:
    runs-on: linux-x64-small
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git User
        shell: bash
        run: |
          git config --global user.name "Sai Kiran Madupu"
          git config --global user.email "saikiran.madupu@gmail.com"

      - name: Backup E2E testing Branch
        shell: bash
        run: |
          git branch -D backup-e2e-testing 2>/dev/null || true
          git push origin --delete backup-e2e-testing
          git fetch origin e2e-testing
          git checkout -b backup-e2e-testing origin/e2e-testing
          git push origin backup-e2e-testing

      - name: Delete E2E testing Branch
        shell: bash
        run: |
          git push origin --delete e2e-testing
          git branch -D e2e-testing 2>/dev/null || true

      - name: Recreate E2E testing Branch
        shell: bash
        run: |
          git checkout main
          git pull origin main
          git checkout -b e2e-testing
          git push origin e2e-testing
