name: Recreate E2E Testing Branch

on:
  workflow_dispatch:

permissions:
  actions: write
  checks: write
  contents: write
  deployments: read
  id-token: write
  issues: read
  pull-requests: write
  statuses: read

jobs:
  recreate-e2e-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git User
        shell: bash
        run: |
          git config --global user.name "Sai Kiran Madupu"
          git config --global user.email "saikiran.madupu@gmail.com"

      - name: Backup E2E testing Branch
        shell: bash
        run: |
          if git ls-remote --heads origin backup-e2e-testing | grep -q backup-e2e-testing; then
            git push origin --delete backup-e2e-testing
          else
            echo "→ remote backup-e2e-testing doesn’t exist, skipping deletion"
          fi
          git fetch origin e2e-testing
          git checkout -b backup-e2e-testing origin/e2e-testing
          git push origin backup-e2e-testing

      - name: Delete E2E branch protection rule
        shell: bash
        run: |
          curl -X DELETE \
            -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/1919kiran/github-actions-test/branches/e2e-testing/protection

      - name: Delete E2E testing Branch
        shell: bash
        run: |
          git push origin --delete e2e-testing
          git branch -D e2e-testing 2>/dev/null || true

      - name: Recreate E2E branch protection rule
        shell: bash
        run: |
          curl -X PUT \
            -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/1919kiran/github-actions-test/branches/e2e-testing/protection \
            -d '{
              "required_status_checks": null,
              "enforce_admins": true,
              "required_pull_request_reviews": {
                "dismiss_stale_reviews": false,
                "require_code_owner_reviews": false,
                "required_approving_review_count": 1,
                "bypass_pull_request_allowances": {
                  "users": ["1919kiran"]
                }
              },
              "restrictions": null,
              "required_linear_history": true,
              "allow_force_pushes": {
                "enabled": true,
                "users": ["1919kiran"]
              },
              "allow_deletions": false
            }'


      - name: Recreate E2E testing Branch
        shell: bash
        run: |
          git checkout main
          git pull origin main
          git checkout -b e2e-testing
          git push origin e2e-testing
